CREATE TABLE address
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    address_line_1 VARCHAR(255)                            NOT NULL,
    postal_code    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_address PRIMARY KEY (id)
);

CREATE TABLE country
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    abbreviation VARCHAR(5)                              NOT NULL,
    CONSTRAINT pk_country PRIMARY KEY (id)
);

CREATE TABLE state_province
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    abbreviation VARCHAR(2)                              NOT NULL,
    country_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_state_province PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name        VARCHAR(255)                            NOT NULL,
    last_name         VARCHAR(255)                            NOT NULL,
    email             VARCHAR(255)                            NOT NULL,
    address_id        BIGINT                                  NOT NULL,
    state_province_id BIGINT,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE country
    ADD CONSTRAINT uc_country_abbreviation UNIQUE (abbreviation);

ALTER TABLE country
    ADD CONSTRAINT uc_country_name UNIQUE (name);

ALTER TABLE state_province
    ADD CONSTRAINT uc_state_province_abbreviation UNIQUE (abbreviation);

ALTER TABLE state_province
    ADD CONSTRAINT uc_state_province_name UNIQUE (name);

ALTER TABLE "user"
    ADD CONSTRAINT uc_user_email UNIQUE (email);

ALTER TABLE state_province
    ADD CONSTRAINT FK_STATE_PROVINCE_ON_COUNTRY FOREIGN KEY (country_id) REFERENCES country (id);

ALTER TABLE "user"
    ADD CONSTRAINT FK_USER_ON_ADDRESS FOREIGN KEY (address_id) REFERENCES address (id);

ALTER TABLE "user"
    ADD CONSTRAINT FK_USER_ON_STATE_PROVINCE FOREIGN KEY (state_province_id) REFERENCES state_province (id);